package com.zubair.kotlinjetpack.view

import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.navigation.Navigation
import androidx.recyclerview.widget.RecyclerView
import com.zubair.kotlinjetpack.R
import com.zubair.kotlinjetpack.databinding.DogRowBinding
import com.zubair.kotlinjetpack.model.DogBreed
import kotlinx.android.synthetic.main.dog_row.view.*

class DogListAdapter(private val dogList: ArrayList<DogBreed>):
    RecyclerView.Adapter<DogListAdapter.DogViewHolder>(), DogClickListener {

    fun updateDogList(newList : List<DogBreed>){
        dogList.clear()
        dogList.addAll(newList)
        notifyDataSetChanged()
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): DogViewHolder =
        //Data binding code, notice the onBindViewHolder
        DogViewHolder(DataBindingUtil.inflate(
            LayoutInflater.from(parent.context),
            R.layout.dog_row, parent, false))

    override fun getItemCount(): Int = dogList.size

    override fun onBindViewHolder(holder: DogViewHolder, position: Int) {
        holder.view.dog = dogList[position]
        holder.view.listener = this
    }

    override fun onDogClicked(view: View) {
        val action = ListFragmentDirections.navigateToDetailFragment()
        action.dogUuid = view.dog_uuid.text.toString().toInt()
        Navigation.findNavController(view).navigate(action)
    }

    //DogBinding was generated by the system when we added the layout tag in the dog_row.xml
    class DogViewHolder(var view: DogRowBinding) : RecyclerView.ViewHolder(view.root)

}