package com.zubair.kotlinjetpack.view

import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.recyclerview.widget.RecyclerView
import com.zubair.kotlinjetpack.R
import com.zubair.kotlinjetpack.databinding.DogRowBinding
import com.zubair.kotlinjetpack.model.DogBreed

class DogListAdapter(private val dogList: ArrayList<DogBreed>): RecyclerView.Adapter<DogListAdapter.DogViewHolder>() {

    fun updateDogList(newList : List<DogBreed>){
        dogList.clear()
        dogList.addAll(newList)
        notifyDataSetChanged()
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): DogViewHolder =
       /* DogViewHolder(LayoutInflater.from(parent.context).
            inflate(R.layout.dog_row, parent, false))
          For data binding VV   */
        DogViewHolder(DataBindingUtil.inflate(
            LayoutInflater.from(parent.context),
            R.layout.dog_row, parent, false))

    override fun getItemCount(): Int = dogList.size

    override fun onBindViewHolder(holder: DogViewHolder, position: Int) =
        holder.bind(dogList[position])

    //DogBinding was generated by the system when we added the layout tag in the dog_row.xml
    class DogViewHolder(var view: DogRowBinding) : RecyclerView.ViewHolder(view.root){

        fun bind(dogItem: DogBreed) {
            view.dog = dogItem
        }
    }

}